#!/bin/bash

#read file name and work with it
read -p "please input the file name(e.g example.gjf or example.xyz):" name
#echo $name
read -p "please input the number of atoms:" number
i=1
tail -n $[number+i] $name > temp
awk '{print $2","$3","$4}' temp > coord
python python.py
